console.log("ARITHMETIC OPERATOR")

console.log("1"+2)
console.log(1+"2")
console.log(1+2)
console.log("1"+2+2)
console.log(1+2+"2")
console.log(+true)
console.log(+"")
console.log(+"sara")
console.log(+false)

console.log("COMPARISON OPERATORS")
console.log("2">1)
console.log("02">"01")

console.log("DIFFERENCE BETWEEN == AND >= AND >")
console.log(null>0)
console.log(null==0)
console.log(null>=0)
console.log(undefined == 0)
console.log(undefined > 0)
console.log(undefined <0)

console.log("DIFFERENCE == AND ===")
console.log("2"=== 2)
console.log(2===2)
console.log("2"==2)
console.log(2==2)